import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Activity, Braces, CheckCircle2, Clock3, Copy, Database, Download, Filter, GitBranch, Network, Play, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProofBadge } from "@/components/trustable/Chrome";
import { DrillDown } from "@/components/trustable/DrillDown";
import { ReportActions } from "@/components/trustable/ReportActions";
import { pageMeta } from "@/lib/site";

export const Route = createFileRoute("/_authenticated/app/api-console")({ head: () => pageMeta({ title: "API Console — Trustable", description: "Inspect Trustable API calls, schemas, telemetry, and organization graph wiring.", path: "/app/api-console", index: false }), component: ApiConsole });
const ENDPOINTS = [
  ["POST", "/v1/trustable/flows/evaluate", "Flow decision and policy evaluation", "Live"], ["GET", "/v1/tenants/{tenant}/posture", "Tenant risk posture snapshot", "Live"], ["GET", "/v1/audit/events", "Tamper-evident event stream", "Live"], ["POST", "/v1/evidence/analyze", "Evidence control-gap analysis", "Live"], ["POST", "/v1/organic/negotiate", "Advocate endpoint negotiation", "Reference"], ["GET", "/v1/organizations/{id}/graph", "Organization graph and graphlets", "Reference"], ["POST", "/v1/advocates/escalate", "Sub-command resource escalation", "Reference"],
] as const;
const CALLS = Array.from({ length: 18 }, (_, i) => ({ id: `req_${8421 + i}`, method: i % 3 ? "POST" : "GET", path: ENDPOINTS[i % ENDPOINTS.length]![1], status: i % 9 === 0 ? 202 : 200, latency: 31 + i * 7, at: `${i + 1}m ago`, actor: i % 2 ? "Bob Henderson" : "Sally Chen", trace: `tr_${(98211 + i).toString(16)}` }));

function ApiConsole() { const [q, setQ] = useState(""); const [selected, setSelected] = useState(CALLS[0]!); const matches = useMemo(() => CALLS.filter((c) => JSON.stringify(c).toLowerCase().includes(q.toLowerCase())), [q]); return <div className="-mx-3 space-y-5 lg:-mx-10">
  <div className="flex flex-wrap items-end justify-between gap-3 px-3 lg:px-10"><div><p className="eyebrow">EngineWare-powered interface · expert mode</p><h1 className="text-3xl font-bold">Trustable API Console</h1><p className="mt-1 text-sm text-muted-foreground">Flip from simple outcomes to every wire, policy gate, call, parameter, and receipt.</p></div><div className="flex gap-2"><ProofBadge kind="live" /><ReportActions title="Trustable API Console" data={{ endpoints: ENDPOINTS, calls: CALLS }} /></div></div>
  <div className="mx-3 rounded-md border border-warning/40 bg-warning/10 px-4 py-3 text-xs font-semibold text-warning lg:mx-10">CONFIDENTIAL · PROPRIETARY ENGINEWARE.AI IP · CREATED AND OWNED BY CHRISTOPHER WARE · NOT FOR REDISTRIBUTION</div>
  <div className="grid min-h-[700px] overflow-hidden border-y border-border bg-card/35 xl:grid-cols-[300px_1fr_360px]">
    <aside className="border-r border-border p-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search endpoints…" value={q} onChange={(e) => setQ(e.target.value)} /></div><div className="mt-4 flex items-center justify-between"><p className="eyebrow">Endpoint catalog</p><Button size="icon" variant="ghost" title="Filter endpoints"><Filter className="h-4 w-4" /></Button></div><div className="mt-2 space-y-1">{ENDPOINTS.filter((e) => `${e[0]} ${e[1]} ${e[2]}`.toLowerCase().includes(q.toLowerCase())).map((e) => <DrillDown key={e[1]} title={e[1]} description={e[2]} trigger={<Button variant="ghost" className="h-auto w-full justify-start gap-2 border border-transparent px-2 py-2 text-left hover:border-primary/30"><span className={`font-mono text-[9px] ${e[0] === "GET" ? "text-success" : "text-primary"}`}>{e[0]}</span><span className="min-w-0 flex-1 truncate font-mono text-[10px]">{e[1]}</span><span className={`text-[8px] uppercase ${e[3] === "Live" ? "text-success" : "text-warning"}`}>{e[3]}</span></Button>}><p className="text-sm">{e[2]}</p><p className="mt-3 text-xs text-muted-foreground">Schemas, enums, saved queries, and generated documentation are available in this endpoint workspace.</p></DrillDown>)}</div></aside>
    <main className="min-w-0 p-5"><div className="grid gap-3 sm:grid-cols-4"><Metric icon={Activity} label="Calls" value="18" /><Metric icon={Clock3} label="p95 latency" value="143ms" /><Metric icon={ShieldCheck} label="Gates passed" value="97.8%" /><Metric icon={GitBranch} label="Graphlets" value="24" /></div><div className="mt-5 flex flex-wrap items-center justify-between gap-2"><div><p className="eyebrow">Request telemetry</p><h2 className="font-semibold">Live call stream</h2></div><div className="flex gap-2"><Button variant="outline" size="sm"><Download className="mr-1 h-4 w-4" />OAS spec</Button><Button variant="outline" size="sm"><Network className="mr-1 h-4 w-4" />Build sub-spec</Button></div></div><div className="mt-3 overflow-auto rounded border border-border"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-muted/70 text-muted-foreground"><tr><th className="p-2">Request</th><th>Path</th><th>Status</th><th>Latency</th><th>Actor</th><th>Time</th></tr></thead><tbody className="divide-y divide-border">{matches.map((c) => <tr key={c.id} onClick={() => setSelected(c)} className={`cursor-pointer hover:bg-accent/60 ${selected.id === c.id ? "bg-primary/10" : ""}`}><td className="p-2 font-mono">{c.method} · {c.id}</td><td className="font-mono">{c.path}</td><td className="text-success">{c.status}</td><td>{c.latency}ms</td><td>{c.actor}</td><td>{c.at}</td></tr>)}</tbody></table></div>
      <section className="mt-5 rounded border border-border bg-background/60 p-4"><div className="flex items-center justify-between"><div><p className="eyebrow">Organization graph</p><h2 className="font-semibold">Advocates → gates → resources</h2></div><ProofBadge kind="reference" /></div><div className="mt-5 flex flex-wrap items-center justify-center gap-2">{["Bob advocate", "Sally advocate", "Department captain", "Policy router", "Customer APIs", "Impact ledger"].map((n, i) => <div key={n} className="flex items-center gap-2"><DrillDown title={n} description="EngineWare organic API architecture node." trigger={<Button variant="outline" className="h-16 border-primary/30 bg-primary/5"><span><span className="block text-xs font-semibold">{n}</span><span className="block text-[9px] uppercase text-muted-foreground">{i < 2 ? "Personal graphlet" : i === 2 ? "Sub-command" : "Negotiated service"}</span></span></Button>}><p className="text-sm">This architecture is pre-wired in the presentation layer and awaits a verified EngineWare connector contract in this repository.</p></DrillDown>{i < 5 && <span className="text-primary">→</span>}</div>)}</div></section>
    </main>
    <aside className="border-l border-border bg-background/55 p-4"><div className="flex items-center justify-between"><div><p className="eyebrow">Request inspector</p><h2 className="font-mono text-sm">{selected.id}</h2></div><Button size="icon" variant="ghost" onClick={() => navigator.clipboard.writeText(JSON.stringify(selected, null, 2))}><Copy className="h-4 w-4" /></Button></div><div className="mt-4 grid grid-cols-2 gap-2"><Metric icon={CheckCircle2} label="Status" value={String(selected.status)} /><Metric icon={Clock3} label="Latency" value={`${selected.latency}ms`} /></div><div className="mt-4 space-y-4"><Code title="Sanitized request" value={{ method: selected.method, path: selected.path, headers: { authorization: "Bearer [REDACTED]", "x-trace-id": selected.trace }, body: { tenant: "[SCOPED]", input: "[SANITIZED]" } }} /><Code title="Policy gates" value={{ authentication: "passed", authorization: "passed", tenantScope: "passed", pii: selected.status === 202 ? "human_review" : "passed", ledger: "appended" }} /></div><Button className="mt-4 w-full"><Play className="mr-2 h-4 w-4" />Create query from call</Button><p className="mt-3 text-[10px] leading-relaxed text-muted-foreground">Live telemetry shown from this prototype’s current surfaces. EngineWare advocate negotiation, SQL Server source-of-truth synchronization, and self-mutating customer schemas are marked Reference until connected and verified.</p></aside>
  </div>
</div>; }
function Metric({ icon: I, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="rounded border border-border bg-card p-3 shadow-lg"><I className="h-4 w-4 text-primary" /><p className="mt-2 font-display text-xl font-bold">{value}</p><p className="text-[9px] uppercase text-muted-foreground">{label}</p></div>; }
function Code({ title, value }: { title: string; value: unknown }) { return <div><p className="mb-2 flex items-center gap-2 text-xs font-semibold"><Braces className="h-3.5 w-3.5 text-primary" />{title}</p><pre className="max-h-56 overflow-auto rounded border border-border bg-muted/50 p-3 text-[10px]">{JSON.stringify(value, null, 2)}</pre></div>; }