import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { AlertTriangle, ArrowRight, BarChart3, Boxes, Braces, Check, ChevronRight, Clock3, Copy, Database, FileSpreadsheet, GitBranch, Mail, MoreHorizontal, Play, Save, Search, Share2, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { runFlow } from "@/lib/trustable.functions";
import { useWorkspace } from "@/hooks/use-workspace";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ProofBadge, StatusPill } from "@/components/trustable/Chrome";
import { EmphasizedControl, EmphasizedField } from "@/components/trustable/EmphasizedField";
import { DrillDown, drillableClass } from "@/components/trustable/DrillDown";
import { ReportActions } from "@/components/trustable/ReportActions";
import { pageMeta } from "@/lib/site";

export const Route = createFileRoute("/_authenticated/app/flow")({
  head: () => pageMeta({ title: "Trustable Flow Builder", description: "Build, inspect, and measure governed enterprise workflows.", path: "/app/flow", index: false }),
  component: FlowPage,
});

type Template = { id: string; title: string; task: string; role: string; department: string; category: string; risk: "Low" | "Review" | "Elevated"; apps: string[]; minutes: number; created: string; used: string };
const SEEDS = [
  ["Quarterly contractor access review", "Each quarter, I review which contractors still have access to our 14 SaaS tools, including their home addresses, then email an Excel file to Security.", "IT Admin", "IT", "Access", "Elevated", ["Entra ID", "Excel", "Outlook"], 180],
  ["Pipeline hygiene", "Every Monday I reconcile pipeline owners, correct account stages, and email a summary to the revenue leadership team.", "Sales Ops", "Revenue", "Reporting", "Low", ["Salesforce", "Excel", "Outlook"], 75],
  ["Leadership action register", "After each leadership meeting, turn notes into action items with owners and deadlines and publish them to the delivery board.", "Chief of Staff", "Executive", "Coordination", "Low", ["Teams", "Jira"], 45],
  ["Vendor risk intake", "Collect security questionnaires and policies from new vendors, identify unanswered controls, and route material gaps to Security.", "Risk Analyst", "Security", "Risk", "Review", ["SharePoint", "Jira", "Outlook"], 120],
  ["Joiner access package", "When a new employee starts, create the approved account package for their department and notify their manager.", "HR Partner", "People", "Onboarding", "Review", ["Workday", "Entra ID", "Teams"], 60],
  ["Invoice exception review", "Find invoices above policy thresholds, attach supporting records, and send exceptions to the finance approver.", "Controller", "Finance", "Approval", "Review", ["SQL Server", "Excel", "Outlook"], 90],
] as const;
const TEMPLATES: Template[] = Array.from({ length: 24 }, (_, i) => { const s = SEEDS[i % SEEDS.length]!; return { id: `TF-${String(i + 1).padStart(3, "0")}`, title: i < SEEDS.length ? s[0] : `${s[0]} · ${Math.floor(i / SEEDS.length) + 1}`, task: s[1], role: s[2], department: s[3], category: s[4], risk: s[5], apps: [...s[6]], minutes: s[7] + (i % 4) * 10, created: `${3 + i} days ago`, used: i % 5 === 0 ? "Never" : `${(i % 8) + 1}h ago` }; });
type Result = Awaited<ReturnType<typeof runFlow>>;

function FlowPage() {
  const { data } = useWorkspace(); const run = useServerFn(runFlow); const qc = useQueryClient();
  const [selected, setSelected] = useState(TEMPLATES[0]!); const [task, setTask] = useState(selected.task); const [dept, setDept] = useState(""); const [operator, setOperator] = useState("Bob Henderson");
  const [query, setQuery] = useState(""); const [role, setRole] = useState("all"); const [category, setCategory] = useState("all"); const [expert, setExpert] = useState(false); const [busy, setBusy] = useState(false); const [result, setResult] = useState<Result | null>(null);
  const canRun = data && data.role !== "auditor"; const deptId = dept || data?.departments[0]?.id || "";
  const visible = useMemo(() => TEMPLATES.filter((t) => `${t.title} ${t.task} ${t.role} ${t.department} ${t.category} ${t.apps.join(" ")}`.toLowerCase().includes(query.toLowerCase()) && (role === "all" || t.role === role) && (category === "all" || t.category === category)), [query, role, category]);
  const choose = (t: Template) => { setSelected(t); setTask(t.task); setResult(null); };
  async function go() { setBusy(true); setResult(null); try { const r = await run({ data: { task, departmentId: deptId, operatorLabel: operator } }); setResult(r); if (!r.ok) toast.error(r.reason); else toast.success(r.status === "executed" ? `Flow ready. ${r.minutes} minutes returned this week.` : "Trustable held this flow for human review."); qc.invalidateQueries({ queryKey: ["workspace"] }); } catch (e) { toast.error(e instanceof Error ? e.message : "Flow could not be evaluated"); } finally { setBusy(false); } }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Two-week enterprise pilot · Bob’s workspace</p><h1 className="text-3xl font-bold">Build a Trustable Flow</h1><p className="mt-1 text-sm text-muted-foreground">Describe the work. Trustable maps the systems, checks the risk, and shows the value.</p></div><div className="flex gap-2"><ProofBadge kind="live" /><Button variant={expert ? "default" : "outline"} onClick={() => setExpert((v) => !v)}><Braces className="mr-2 h-4 w-4" />{expert ? "Simple view" : "Show wiring"}</Button></div></div>
    <div className="rounded-md border border-warning/40 bg-warning/10 px-4 py-3 text-xs font-semibold text-warning">CONFIDENTIAL · PROPRIETARY ENGINEWARE.AI IP · OWNED BY CHRISTOPHER WARE · NOT FOR REDISTRIBUTION</div>
    <div className="grid gap-5 xl:grid-cols-[310px_minmax(360px,520px)_1fr]">
      <aside className="panel max-h-[790px] overflow-hidden p-4"><div className="flex items-center justify-between"><div><p className="eyebrow">Flow catalog</p><h2 className="font-semibold">{visible.length} matched flows</h2></div><Boxes className="h-5 w-5 text-primary" /></div>
        <div className="mt-3 space-y-2"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search tasks, roles, apps…" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="grid grid-cols-2 gap-2"><Select value={role} onValueChange={setRole}><SelectTrigger><SelectValue placeholder="Choose role…" /></SelectTrigger><SelectContent><SelectItem value="all">All roles (recommended)</SelectItem>{[...new Set(TEMPLATES.map((t) => t.role))].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}<SelectItem value="other">Other / custom</SelectItem></SelectContent></Select><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue placeholder="Choose type…" /></SelectTrigger><SelectContent><SelectItem value="all">All types (recommended)</SelectItem>{[...new Set(TEMPLATES.map((t) => t.category))].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}<SelectItem value="other">Other / custom</SelectItem></SelectContent></Select></div>{(role === "other" || category === "other") && <Input placeholder="Describe your custom role or flow type…" aria-label="Custom role or flow type" />}</div>
        <div className="mt-3 max-h-[640px] space-y-2 overflow-y-auto pr-1">{visible.map((t) => <Button key={t.id} variant="ghost" onClick={() => choose(t)} className={`h-auto w-full justify-start whitespace-normal border p-3 text-left ${selected.id === t.id ? "border-primary bg-primary/10" : "border-border bg-card/40"}`}><div className="w-full"><div className="flex items-start gap-2"><FlowIcon category={t.category} /><span className="flex-1 font-medium leading-tight">{t.title}</span><ChevronRight className="h-4 w-4 shrink-0" /></div><div className="mt-2 flex flex-wrap gap-1"><Tag>{t.role}</Tag><Tag>{t.department}</Tag><Risk value={t.risk} /></div><p className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>Created {t.created}</span><span>Used {t.used}</span></p></div></Button>)}</div>
      </aside>
      <main className="mx-auto w-full max-w-[480px] rounded-[32px] border-[6px] border-foreground/10 bg-card p-2 shadow-[0_35px_90px_-35px_oklch(0_0_0/95%)]"><div className="rounded-[24px] border border-border bg-background p-5"><div className="mx-auto mb-4 h-1.5 w-20 rounded-full bg-muted" /><div className="flex items-center justify-between"><div><p className="eyebrow">Hello, Bob</p><h2 className="text-xl font-bold">What should we improve?</h2></div><UserRound className="h-8 w-8 rounded-full bg-primary/10 p-1.5 text-primary" /></div>
        {!canRun && <p className="mt-3 rounded border border-warning/40 bg-warning/10 p-2 text-xs text-warning">Your auditor role is read-only.</p>}
        <div className="mt-4 space-y-3"><EmphasizedField label="Describe the work" hint="Use plain language. Suggestions and mapped services update as you type." value={task} onChange={(v) => setTask(v.slice(0, 1000))} library><Textarea rows={7} value={task} onChange={(e) => setTask(e.target.value)} maxLength={1000} /></EmphasizedField>
          <div className="rounded-lg border border-primary/25 bg-primary/5 p-3"><p className="flex items-center gap-2 text-xs font-semibold"><Sparkles className="h-4 w-4 text-primary" />Trustable recognized</p><div className="mt-2 flex flex-wrap gap-1">{selected.apps.map((app) => <Tag key={app}>{app}</Tag>)}<Tag>Quarterly trigger</Tag>{task.toLowerCase().includes("address") && <Risk value="Elevated" />}</div></div>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><EmphasizedField label="Person" hint="The named owner responsible for this flow." value={operator} onChange={setOperator}><Input value={operator} onChange={(e) => setOperator(e.target.value)} placeholder="e.g. Bob Henderson" autoComplete="name" /></EmphasizedField><EmphasizedControl label="Team" hint="Choose the authorized team that owns this work."><Select value={deptId} onValueChange={setDept}><SelectTrigger><SelectValue placeholder="Choose a team…" /></SelectTrigger><SelectContent>{data?.departments.map((d) => <SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}<SelectItem value="other">Other / custom</SelectItem></SelectContent></Select>{deptId === "other" && <Input className="mt-2" placeholder="Enter a custom team…" aria-label="Custom team" />}</EmphasizedControl></div>
          <div className="grid grid-cols-3 gap-2 text-center"><Mini label="Weekly value" value={`${selected.minutes}m`} /><Mini label="Systems" value={String(selected.apps.length)} /><Mini label="Checks" value="5/5" /></div>
          <Button onClick={go} disabled={!canRun || busy || task.trim().length < 8} className="w-full" size="lg"><Play className="mr-2 h-4 w-4" />{busy ? "Mapping and checking…" : "Check and build my flow"}</Button>
          <div className="grid grid-cols-4 gap-1"><Button size="sm" variant="ghost" title="Save draft" onClick={() => toast.message("Session draft is ready; persistent flow storage requires the EngineWare contract.")}><Save className="h-4 w-4" /></Button><Button size="sm" variant="ghost" title="Copy flow" onClick={() => navigator.clipboard.writeText(task)}><Copy className="h-4 w-4" /></Button><Button size="sm" variant="ghost" title="Share flow" onClick={() => navigator.share?.({ title: selected.title, text: task })}><Share2 className="h-4 w-4" /></Button><ReportActions title={selected.title} data={{ ...selected, task }} className="px-2" /></div>
        </div></div></main>
      <aside className="panel min-h-[620px] overflow-hidden p-0"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-border px-4 py-3"><div className="min-w-0"><p className="eyebrow">Live flow whiteboard</p><h2 className="truncate font-semibold">Your flow is taking shape</h2></div><GitBranch className="h-5 w-5 shrink-0 text-primary" /></div>
        <Tabs defaultValue="map" className="min-w-0"><TabsList className="h-10 w-full justify-start overflow-x-auto rounded-none border-b border-border bg-card/50 px-2"><TabsTrigger value="map" className="text-xs">Map</TabsTrigger><TabsTrigger value="checks" className="text-xs">Safety checks</TabsTrigger><TabsTrigger value="wiring" className="text-xs">Wiring</TabsTrigger><TabsTrigger value="outcome" className="text-xs">Outcome</TabsTrigger></TabsList>
          <TabsContent value="map" className="m-0 p-4"><FlowMap apps={selected.apps} risky={task.toLowerCase().includes("address") || task.toLowerCase().includes("ssn")} /></TabsContent>
          <TabsContent value="checks" className="m-0 space-y-3 p-4"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><CheckRow text="Identity and role confirmed" /><CheckRow text="Systems mapped" /><CheckRow text="Sensitive data classified" warn={task.toLowerCase().includes("address")} /><CheckRow text="Audit receipt enabled" /></div>{task.toLowerCase().includes("address") ? <div className="rounded-lg border border-warning/40 bg-warning/10 p-3"><p className="flex gap-2 text-sm font-semibold text-warning"><AlertTriangle className="h-4 w-4" />Sensitive-data path detected</p><p className="mt-1 text-xs text-muted-foreground">Home addresses require a human approval gate before export.</p><Button asChild size="sm" variant="outline" className="mt-3"><Link to="/app/redteam">Send to Red Team <ArrowRight className="ml-1 h-3 w-3" /></Link></Button></div> : <div className="border border-success/30 bg-success/10 p-3 text-xs text-success">All currently mapped paths pass the visible safety checks.</div>}</TabsContent>
          <TabsContent value="wiring" className="m-0 p-4"><div className="rounded-lg border border-border bg-muted/40 p-3"><div className="flex items-center justify-between"><div><p className="font-mono text-xs text-primary">runFlow · authenticated server action</p><p className="mt-1 text-[9px] font-semibold uppercase text-muted-foreground">OASA REST mapping · Reference architecture</p></div><Button size="icon" variant="ghost" onClick={() => navigator.clipboard.writeText(JSON.stringify({ operator, departmentId: deptId, task: "[SANITIZED USER INPUT]" }, null, 2))}><Copy className="h-4 w-4" /></Button></div><pre className="mt-3 max-h-64 overflow-auto border border-border bg-background/60 p-3 text-[10px] text-muted-foreground">{JSON.stringify({ operator, departmentId: deptId, task: "[SANITIZED USER INPUT]", controls: ["rbac", "pii", "confidence", "ledger"] }, null, 2)}</pre><Button asChild variant="outline" size="sm" className="mt-3 w-full"><Link to="/app/api-console">Inspect in OASA Console</Link></Button><div className="mt-3 flex items-center gap-2"><ProofBadge kind="reference" /><p className="text-[10px] text-muted-foreground">Public OASA endpoint negotiation awaits a verified EngineWare.ai connector contract.</p></div></div></TabsContent>
          <TabsContent value="outcome" className="m-0 p-4">{result?.ok ? <div className="rounded-lg border border-success/35 bg-success/10 p-4"><p className="flex items-center gap-2 font-semibold text-success"><Check className="h-5 w-5" />You built a governed flow</p><div className="mt-3 flex items-center gap-2"><StatusPill status={result.status} /><span className="font-mono text-xs">{result.latencyMs}ms · +{result.minutes}m</span></div><p className="mt-2 text-sm">This is measurable work you can own, improve, and combine into a larger Trustable solution.</p><DrillDown title="Validated flow detail" description="Full decision and audit-ready output." trigger={<Button className="mt-3" variant="outline" size="sm">Inspect every detail</Button>}><pre className="max-h-96 overflow-auto text-xs">{JSON.stringify(result, null, 2)}</pre></DrillDown></div> : <div className="flex min-h-64 flex-col items-center justify-center border border-dashed border-border p-6 text-center"><BarChart3 className="h-8 w-8 text-muted-foreground" /><h3 className="mt-3 font-semibold">Your measured outcome appears here</h3><p className="mt-2 max-w-sm text-xs text-muted-foreground">Check and build the flow to receive its governed status, latency, time returned, and audit-ready detail.</p></div>}</TabsContent>
        </Tabs>
      </aside>
    </div>
  </div>;
}

function FlowMap({ apps, risky }: { apps: string[]; risky: boolean }) { const nodes = [{ icon: Clock3, label: "Quarterly", kind: "Trigger", position: "left-3 top-1/2 -translate-y-1/2" }, ...apps.slice(0, 3).map((label, i) => ({ icon: i === 0 ? Database : i === 1 ? FileSpreadsheet : Mail, label, kind: "Mapped service", position: i === 0 ? "left-[30%] top-6" : i === 1 ? "left-[30%] bottom-6" : "left-[54%] top-1/2 -translate-y-1/2" })), { icon: ShieldCheck, label: risky ? "Human approval" : "Trustable gate", kind: risky ? "Required" : "Verified", position: "right-[18%] top-1/2 -translate-y-1/2" }, { icon: BarChart3, label: "Impact receipt", kind: "Measured", position: "right-3 top-1/2 -translate-y-1/2" }]; return <div><div className="mb-3 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2"><p className="text-xs text-muted-foreground">Select any node to inspect its parameters, policy evaluation, and downstream edges.</p><span className="flex items-center gap-1 font-mono text-[9px] text-success"><span className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />Mapping</span></div><div className="relative h-[390px] overflow-hidden border border-border bg-background/55 shadow-inner sm:h-[430px]"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(to_right,var(--border)_1px,transparent_1px),linear-gradient(to_bottom,var(--border)_1px,transparent_1px)] [background-size:24px_24px]" /><svg className="pointer-events-none absolute inset-0 h-full w-full" aria-hidden="true"><path d="M 70 210 C 135 210, 130 90, 190 90 M 70 210 C 135 210, 130 340, 190 340 M 250 90 C 300 90, 295 210, 340 210 M 250 340 C 300 340, 295 210, 340 210 M 405 210 L 475 210 M 540 210 L 610 210" fill="none" stroke="var(--primary)" strokeOpacity="0.42" strokeWidth="2" strokeDasharray="7 6" /></svg>{nodes.map(({ icon: I, label, kind, position }, i) => <DrillDown key={`${label}-${i}`} title={label} description={`${kind} node in the current flow graph.`} trigger={<Button variant="outline" className={cn("absolute z-10 h-auto w-24 flex-col gap-1 border-primary/30 bg-card/95 px-2 py-3 text-center shadow-xl sm:w-28", position, kind === "Required" && "border-warning/60 bg-warning/10")}><span className="flex h-8 w-8 items-center justify-center rounded-full border border-primary/30 bg-background"><I className="h-4 w-4 text-primary" /></span><span className="max-w-full truncate text-[10px] font-semibold">{label}</span><span className="font-mono text-[8px] uppercase text-muted-foreground">{kind} · {18 + i * 11}ms</span></Button>}><p className="text-sm">Node telemetry, sanitized parameters, active gates, latency, and downstream edges are available here.</p></DrillDown>)}</div><div className="mt-3 flex flex-wrap gap-2"><Tag>6 nodes</Tag><Tag>{apps.length + 2} edges</Tag><Tag>{risky ? "1 approval gate" : "All gates passed"}</Tag><Tag>Audit enabled</Tag></div></div>; }
function FlowIcon({ category }: { category: string }) { const I = category === "Reporting" ? BarChart3 : category === "Access" ? ShieldCheck : category === "Approval" ? Check : GitBranch; return <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded bg-primary/10"><I className="h-3.5 w-3.5 text-primary" /></span>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded border border-border bg-muted/50 px-1.5 py-0.5 text-[9px] uppercase text-muted-foreground">{children}</span>; }
function Risk({ value }: { value: Template["risk"] }) { return <span className={`rounded border px-1.5 py-0.5 text-[9px] uppercase ${value === "Elevated" ? "border-destructive/40 text-destructive" : value === "Review" ? "border-warning/40 text-warning" : "border-success/40 text-success"}`}>{value}</span>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-border bg-muted/40 p-2"><p className="font-display text-lg font-bold">{value}</p><p className="text-[9px] uppercase text-muted-foreground">{label}</p></div>; }
function CheckRow({ text, warn }: { text: string; warn?: boolean }) { return <div className="flex items-center gap-2 rounded border border-border bg-card p-2 text-xs">{warn ? <AlertTriangle className="h-4 w-4 text-warning" /> : <Check className="h-4 w-4 text-success" />}{text}</div>; }